title: violin's blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://min.violin.site" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings 作者设置
author: violin@-@ # add your name
author-pic: violin-face.jpg # 头像
about-author: To  watch  the  sunrise  must  wait  till  dawn.

# Contact links 社交账号
email: violin@violin.site# 添加你的电子邮箱
phone: +8617306697942# 添加你的手机号码
website: violin.site# 添加你的网站, 不需要添加 http://
weibo: 7273955007
bilibili: 265199586
github: violin321 # 更改为你的github ID
# twitter: 添加你的Twitter ID 格式'@xxxxxx'
# facebook:  添加你的Facebook ID
# instagram:  添加你的 Instagram ID
# pinterest:  添加你的 Pinterest ID
# linkedin:  添加你的linkedin

# Newsletter
#mailchimp: # Add your MailChimp form identifier.

# Disqus 评论
#discus_identifier: mviolin # Add your discus identifier

# Tracker 追踪
#analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
